/**
 * @module pages/index
 *
 *
 * @author montier.elliott@gmail.com
 */
import Head from "next/head";

import Sidebar from "../components/Sidebar";

/**
 * Home Component
 *
 *
 * @component
 * @returns {JSX.Element}
 */
export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>WhatsApp Remix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar />
      </main>
    </>
  );
}
